// Printed by `foundation --help`, and the one page an agent reads before using any of this.
//
// What Foundation offers is an HTTP API, and that is what this describes. Not every agent can run a
// command, so nothing here assumes a shell; where one exists there is a small program that adds the one
// thing HTTP cannot do, and it is described last.
//
// This text is read by the agent, not by the owner, so it is English; everything the owner reads
// (purposes, guidance, the dashboard) stays in the owner's language.
function adapterLines(adapters) {
  if (!adapters) return ['     GET /v1/adapters lists what this server can obtain itself.'];
  const lines = [];
  for (const adapter of adapters.filter(item => item.available)) {
    lines.push('     ' + adapter.id + '  ' + (adapter.service?.name || '') + ' / ' + adapter.access.name + (adapter.variables.length ? '  keeps: ' + adapter.variables.join(', ') : ''));
    if (adapter.ai) lines.push('       ' + adapter.ai);
  }
  const unavailable = adapters.filter(item => !item.available);
  if (unavailable.length) lines.push('     Currently unavailable: ' + unavailable.map(item => item.id).join(', '));
  return lines;
}

export function guide(adapters) {
  return ['Foundation is a store. It keeps what belongs to its owner, and hands it to the commands they run.',
    'One thing is kept: bytes, at a path. Foundation never reads them and has no idea what they are, so anything can go in.',
    'A short string delivered as a variable is what others call a key and a value; a JSON body you read back is a document;',
    'a PEM delivered as a file is a file. Here they are one mechanism, and a kind of content nobody has thought of needs no change.',
    '',
    'It is an HTTP API. Everything below is a request you make yourself, with your key:  Authorization: Bearer fdn_...',
    'Nothing here needs a shell. If you have one, make these requests with `foundation api` rather than curl, and run',
    'commands with `foundation exec`: that way neither your key nor what it reaches ever passes through you. See THE SHELL at the end.',
    'Never ask the owner to paste a key or token into the chat. It goes into the store (see ASKING THE OWNER).', '',
    'YOUR KEY',
    '   Your key is a secret of your own making: 43 URL-safe base64 characters after `fdn_`. Generate one, keep it private,',
    '   and never print it. If you can write a private file, keep it there; otherwise keep it wherever your secrets go.',
    '   POST /v1/keys  {"name": "<what to call you>"}   with your key as the bearer.',
    '     Returns verification_uri and confirmation_code. Give the owner both; they open the URL and type the code.',
    '     Until they do, every other call answers 401 not_approved. Retry GET /v1/me every few seconds. Do not hammer it.',
    '     GET /v1/keys/current shows your request and what happened at its page; DELETE /v1/keys/current cancels it.',
    '   GET /v1/me    who you are, once approved.    PATCH /v1/me {"name"}    DELETE /v1/me    revokes your own key.', '',
    'WHAT IS KEPT',
    '   PUT /v1/secrets/<path>?secret=true',
    '     The body is the bytes, with Content-Type saying what they are. Up to 1MB. Writing the same path again replaces it.',
    '       secret=true     you can no longer read them back; they can only be handed to a command. The owner can still see them.',
    '   GET /v1/secrets?prefix=<path prefix>   what is kept: paths, media types, sizes, version, who wrote it.',
    '   GET /v1/secrets/<path>      the bytes, as written. 403 write_only for a secret.',
    '   DELETE /v1/secrets/<path>',
    '   Paths are your only names, and they mean nothing to Foundation: /-separated segments of letters, digits, dot, underscore, hyphen.',
    '   Group by the first segment when you want things grouped; you cannot search inside what is kept, so make the paths tell you what they are.',
    '   Foundation checks none of it. It cannot tell you something stopped working, so when a command fails on one, replace it.',
    '   The owner sees everything kept, can read any of it, and can remove any of it at any time.', '',
    'HANDING IT TO A COMMAND',
    '   POST /v1/deliver  {"paths": ["aws/access-key-id", {"path": "github/token", "as": "GH_TOKEN"}]}',
    '     Each item is a path, or {path, as, filename}. `as` is the environment variable the command reads it as; leave it out',
    '     and the last segment of the path is used, upper-cased (aws/access-key-id becomes AWS_ACCESS_KEY_ID). `filename` makes',
    '     it a file of that name instead, with `as` holding the path to it -- the only way to hand over bytes a variable cannot carry.',
    '     The same value can go to two names at once; say each one. A name that would collide is refused (409 name_conflict).',
    '     Answering this yourself puts the values in your context. If you can run a command, use exec instead (below).',
    '     github/token          as GH_TOKEN, secret        a key a command reads from the environment',
    '     apple/key             as EXPO_ASC_API_KEY_PATH, filename AuthKey.p8    bytes usable only as a file',
    '     release/2026-09-23    read back yourself         where a procedure got to, for the next conversation', '',
    'FILLING THE STORE: three ways, and only the first is yours alone.',
    '',
    '1. Put it there yourself. Anything you obtained or wrote: PUT /v1/secrets/<path>, above.',
    '',
    '2. ASKING THE OWNER, for what only they can fetch -- an API token, a key, a certificate they must go and create.',
    '   POST /v1/access-requests  {"store": {...}, "purpose": "...", "guidance": "...", "valid_minutes": 30}',
    '     store.path      where it will be kept, beside everything else',
    '     store.label     what they are being asked for, in their language. It titles the screen and names the field.',

    '     store.site      the page where they make it, offered as a link',
    '     store.secret    false lets you read it back afterwards; the default is that you cannot',
    '     store.multiline true for something like a PEM',
    '     purpose         one concrete sentence the owner can judge, in their language',
    '     guidance        the steps they follow (up to 2000 characters). Foundation holds no instructions for anyone else\'s',
    '                     site: look up what to click now, and write it yourself.',
    '   Give the owner the verification_uri (there is no code). When they finish, it is simply kept.',
    '   Ask for what the owner already holds. Never take it through the conversation and put it there yourself.',
    '',
    '3. HAVING FOUNDATION OBTAIN IT, for the few services where nobody else can: an OAuth exchange that needs the',
    '   operator\'s own client secret, or a login relayed once. Foundation then keeps it current and can revoke it.',
    ...adapterLines(adapters),
    '   POST /v1/access-requests  {"adapter": "<id>", "purpose": "...", "valid_minutes": 30}   Give the owner the verification_uri.',
    '   GET /v1/acquisitions   what is connected and the paths each one keeps. Use those paths like any other.',
    '   Wait by retrying GET /v1/secrets every few seconds. Do not hammer it.', '',
    'WHEN IT DOES NOT WORK',
    '   GET /v1/access-requests/current   your own request, and what happened at its page (events).',
    '   events is the raw record, in order: page_opened / page_viewed / connect_started / connect_failed (with a code and',
    '   Foundation\'s own message) / connected / stored / approved / denied / cancelled. What was typed is never recorded.',
    '   DELETE /v1/access-requests/current   cancels it. One pending request at a time; cancel before making a different one.',
    '   Why a registration failed: invalid_values (wrong shape) / invalid_credential (the adapter would not take it) /',
    '   reconnect_required (the service rejected it) / already_connected. A key approval shows its own events at',
    '   GET /v1/keys/current: confirmation_required (a wrong code) / confirmation_locked (5 tries).', '',
    'A PLACE FOR FILES (object storage the owner did not have to sign up for)',
    '   PUT /v1/objects/<key>      body is the bytes; the Content-Type you send is what a reader gets back. Up to 25MB.',
    '   GET /v1/objects/<key>      the bytes. DELETE removes it. GET /v1/objects?prefix=<p>&cursor=<c> lists what is there.',
    '   POST /v1/objects/<key>/link {"minutes":n}   a time-limited URL anyone can read, for a thing that only takes a URL.',
    '   Keys look like a path (a/b/c.txt) but name one whole object: no renaming, no directories, no partial reads or writes.',
    '   This is not a filesystem. If the owner needs one, they need a machine to mount it on.',
    '   Where the bytes live is the owner\'s business: a space lent to them now, a bucket of their own later. Nothing you call changes.', '',
    'WITHOUT A SHELL: an HTTPS request sent for you, with what is kept put in but never shown to you.',
    '   POST /v1/fetch  {"url": "https://api.example.com/v1/items", "method": "POST",',
    '                    "headers": {"authorization": "Bearer {{foundation:github/token}}"}, "body": "..."}',
    '     {{foundation:<path>}} in a header value or the body is replaced with what is kept at that path, here, as it',
    '     goes out. Up to 8 paths. Not in the URL: put a key in a header or the body. body_encoding "base64" sends bytes',
    '     as they are (and puts nothing in them).',
    '     Returns {"response": {status, headers, body, body_encoding}}. Anything that went out is taken back out of the',
    '     answer as [redacted], so a service that echoes a key does not hand it to you. Redirects are returned, not followed.',
    '     Only https on 443, to a public host name; never an address, this server, or anything that resolves to a private',
    '     network. 1MB each way, 20 seconds, 30 a minute. Compression is Foundation\'s to choose, not a header you set.',
    '     With a shell, prefer foundation exec: it reaches anything a command can, not only one HTTPS request.', '',
    'THE SHELL (only if you can run commands). Three commands, each keeping something out of your context.',
    '   Install: npm install -g @tomato414941/foundation   (Node.js 24 or later)',
    '   foundation connect [<url>] [--name <name>]',
    '     Makes the key as a private file and asks for approval. The key is never printed, so it never reaches you.',
    '     Given a URL, it also remembers that server for every later command; run it again when the server moves.',
    '   foundation api <GET|POST|PUT|DELETE|PATCH> </path> [--json <body>] [--from <file>] [--type <media-type>]',
    '     Any request above, with the key attached and the answer printed as it came. Prefer this over curl: reading the key',
    '     file to build a header yourself would put the key in your context, which is the thing this avoids.',
    '   foundation exec [<NAME>[:<filename>]=]<path> [...] -- <command> [args...]',
    '     Runs the command with those in place, and nothing else. Only the child process gets them; a file exists only while',
    '     it runs; FOUNDATION_PATHS lists what was used. The values never pass through you, which is the whole point.',
    '     Use this instead of POST /v1/deliver whenever the point is to run something.',
    '   Environment: FOUNDATION_URL (optional; overrides the remembered server), FOUNDATION_AGENT (optional; your name, e.g. claude / codex), FOUNDATION_RUNTIME_KEY_FILE (optional).',
    '   One key per machine and OS user by default. FOUNDATION_AGENT gives each agent its own key, but any agent running as the',
    '   same OS user can read that file, so it is bookkeeping, not protection. To separate them for real, use separate OS users.', '',
    'RULES',
    '- Never print, log or write out what is delivered. Hand it to a command, and nowhere else.',
    '- Send what is kept only to the service it belongs to. /v1/fetch and exec go wherever you point them.',
    '- Ask for the least you need. Do not request something the work does not use.',
    '- Be honest in name, purpose and label. The owner decides based on them.',
    '- If a request is denied or expires, ask the owner why rather than guessing.',
    '- Use what you receive only for the work it was asked for.',
  ].join('\n');
}
