// Printed by `foundation guide` (and served to MCP clients): the one page an agent reads before using any of this.
//
// What Foundation offers is an HTTP API, and that is what this describes. Not every agent can run a
// command, so nothing here assumes a shell; where one exists there is a small program that adds the one
// thing HTTP cannot do, and it is described last.
//
// This text is read by the agent, not by the owner, so it is English; everything the owner reads
// (purposes, steps, the dashboard) stays in the owner's language.
function connectorLines(connectors) {
  if (!connectors) return ['     GET /v1/connectors lists what this server can obtain itself.'];
  const lines = [];
  for (const connector of connectors.filter(item => item.available)) {
    lines.push('     ' + connector.id + '  ' + (connector.service?.name || '') + ' / ' + connector.access.name + (connector.variables.length ? '  outputs: ' + connector.variables.join(', ') : ''));
    if (connector.ai) lines.push('       ' + connector.ai);
  }
  const unavailable = connectors.filter(item => !item.available);
  if (unavailable.length) lines.push('     Currently unavailable: ' + unavailable.map(item => item.id).join(', '));
  return lines;
}

export function guide(connectors) {
  return ['Foundation keeps user-controlled values and objects, and runs explicitly requested built-in functions.',
    'A saved name identifies bytes. It does not select a service, a connection, a function, or an environment variable.',
    'Storage never invokes a provider: a value saved from a function is an independent snapshot, not a live connection.', '',
    'Everything below is HTTP with your approved key: Authorization: Bearer fdn_...',
    'Nothing here needs a shell. With one, use foundation api to attach the key and foundation exec to deliver values',
    'to a command. api prints responses: use function save options when output should not enter your context.',
    'Never ask the owner to paste passwords, keys or tokens into chat. Use a storage request or OAuth URL instead.', '',
    'YOUR KEY',
    '   Your key is a secret of your own making: 43 URL-safe base64 characters after `fdn_`. Generate one, keep it private,',
    '   and never print it. If you can write a private file, keep it there; otherwise keep it wherever your secrets go.',
    '   POST /v1/keys  {"name": "<what to call you>"}   with your key as the bearer.',
    '     Returns verification_uri and confirmation_code. Give the owner both; they open the URL and type the code.',
    '     Until they do, every other call answers 401 not_approved. Retry GET /v1/keys/current every few seconds. Do not hammer it.',
    '   GET /v1/keys/current    your request and what happened at its page; once approved, also who you are (key).',
    '     Approval also has kind=approve, status=done and result.key_id. A current key, not request completion, authorizes use.',
    '     Revoking a key stops Foundation access; credentials already obtained must be revoked at their provider.',
    '   PATCH /v1/keys/current {"name"}    DELETE /v1/keys/current    cancels the request, or revokes your approved key.', '',
    'WHAT IS KEPT',
    '   PUT /v1/secrets?name=<name>&secret=true    body: raw bytes, up to 1MB. The same exact name replaces that value.',
    '     secret=true blocks direct GET by an access key. The owner can read it; authorized delivery can still return it.',
    '     This is not a boundary against an agent with the approved key. Do not print delivered values into its context.',
    '   GET /v1/secrets    names, sizes, read permissions and timestamps, not contents.',
    '   GET /v1/secrets?prefix=<literal prefix>   optional case-sensitive text filtering, not a directory.',
    '   GET /v1/secrets?name=<name>               bytes, as written; 403 write_only for a secret.',
    '   DELETE /v1/secrets?name=<name>',
    '   URL-encode the name. A name is any text, which is why it travels as a query and not as a path. Names are 1-200 characters without control characters; case, spaces, slashes and punctuation',
    '   remain literal. No normalization, hierarchy, service ownership or automatic renewal is inferred.',
    '   The owner can read, rename or delete any saved value. Stored copies survive OAuth disconnection.', '',
    'HANDING IT TO A COMMAND',
    '   POST /v1/deliveries  {"names": [{"name": "build token", "as": "GH_TOKEN"}]}',
    '     Each item is {name, as, filename?}. as is required: it names the environment variable, independently of name.',
    '     filename makes the bytes a temporary file instead; as holds its local path. Use this for binary or multiline data.',
    '     Up to 16 inputs. Variables and filenames must be distinct; reserved system variables are refused.',
    '     Returns delivery: {environment, files}. No provider check or refresh occurs; expiry of stored bytes is unknown.',
    '     Calling this into an agent context exposes values. Use exec when the intent is to run a local command.', '',
    'FILLING THE STORE',
    '',
    '1. Put it there yourself. Anything you obtained or wrote: PUT /v1/secrets?name=<name>, above.',
    '',
    '2. ASKING THE OWNER, for what only they can fetch -- an API token, a key, a certificate they must go and create.',
    '   POST /v1/requests  {"kind":"store", "input":{"fields":[{...}]}, "purpose":"...", "steps":["..."], "valid_minutes":30}',
    '     fields[].name      suggested name; result.names returns the names the owner chose',
    '     fields[].label     what they are being asked for, in their language. It titles the screen and names the field.',

    '     fields[].site      the page where they make it, offered as a link',
    '     fields[].secret    false lets you read it back afterwards; the default is that you cannot',
    '     fields[].multiline true for something like a PEM',
    '     purpose         one concrete sentence the owner can judge, in their language',
    '     steps           what they do, one string per step (up to 20, 500 characters each, no line breaks). Foundation',
    '                     holds no instructions for anyone else\'s',
    '                     site: look up what to click now, and write it yourself.',
    '   Give the owner the verification_uri (there is no code). When they finish, it is simply kept.',
    '   Ask for what the owner already holds. Never take it through the conversation and put it there yourself.',
    '',
    '3. CONNECTING A SERVICE for later explicit credential processing. OAuth renewal state stays with the connection,',
    '   separate from ordinary saved values. Connecting does not create named values.',
    ...connectorLines(connectors),
    '   POST /v1/requests  {"kind":"connect", "input":{"connector":"<id>"}, "purpose":"...", "valid_minutes":30}   Give the owner the verification_uri.',
    '   Poll GET /v1/requests/<id> every few seconds until done; result.connection_id identifies the connection.',
    '   GET /v1/connections   connection IDs, labels, provider details and available output identifiers.', '',
    'FUNCTIONS',
    '   GET /v1/functions   catalog of built-in operations and their invocation endpoints; no arbitrary-code runtime.',
    '   POST /v1/functions/connection.credentials',
    '     {"connection_id": "<id>", "save": {"<output identifier>": "<chosen saved name>"}}',
    '     Checks or renews that connection and saves only the outputs you explicitly name. Returns saved metadata and',
    '     actual expiry, without credential values. Existing values at those exact names are replaced atomically.',
    '     Omit save to receive delivery directly. Prefer save when invoking from an AI tool; then use exec or http.request.',
    '     Saving creates independent copies: subsequent reads never refresh them; invoke this function again when needed.',
    '     Disconnecting stops future processing, not copies already saved or handed out. Revoke at the provider if needed.', '',
    'WHEN IT DOES NOT WORK',
    '   GET /v1/requests/<id>   one of your requests, and what happened at its page (events).',
    '   GET /v1/requests?status=pending   your requests. Several may be open at once (up to 10).',
    '   events is the raw record, in order: page_opened / page_viewed / connect_started / connect_failed (with a code and',
    '   Foundation\'s own message) / connected / stored / denied / cancelled. What was typed is never recorded.',
    '   DELETE /v1/requests/<id>   cancels it. status is pending / done / denied / cancelled.',
    '   Completion and result are fixed until the request expires, even if the resulting resource changes or is removed.',
    '   Current connection state is at GET /v1/connections. Revoked keys receive 401; their pending requests are cancelled.',
    '   Request feedback expires with the request. A done result is a connection_id or the names saved at completion.',
    '   Why a registration failed: invalid_values (wrong shape) / invalid_credential (the connector would not take it) /',
    '   reconnect_required (the service rejected it) / already_connected. A key approval shows its own events at',
    '   GET /v1/keys/current: confirmation_required (a wrong code) / confirmation_locked (5 tries).', '',
    'A PLACE FOR FILES (object storage the owner did not have to sign up for)',
    '   PUT /v1/objects/<key>      body is the bytes; the Content-Type you send is what a reader gets back. Up to 25MB.',
    '   GET /v1/objects/<key>      the bytes. DELETE removes it. GET /v1/objects?prefix=<p>&cursor=<c> lists what is there.',
    '   POST /v1/objects/<key>/link {"minutes":n}   a time-limited URL anyone can read, for a thing that only takes a URL.',
    '   Keys look like a path (a/b/c.txt) but name one whole object: no renaming, no directories, no partial reads or writes.',
    '   This is not a filesystem. If the owner needs one, they need a machine to mount it on.',
    '   Where the bytes live is the owner\'s business: a space lent to them now, a bucket of their own later. Nothing you call changes.', '',
    'HTTPS REQUEST FUNCTION',
    '   POST /v1/functions/http.request  {"url": "https://api.example.com/v1/items", "method": "POST",',
    '     "headers": {"authorization": "Bearer {{foundation:token}}"}, "bindings": {"token": "build token"}, "body": "..."}',
    '     Each placeholder identifies an input slot. bindings maps slots to exact saved names (including braces or spaces).',
    '     Without bindings, a slot is itself a saved name. Inputs only in headers/body, never in the URL. Up to 8 inputs.',
    '     body_encoding "base64" sends bytes without substitution. Input values are read as stored, never refreshed.',
    '     Returns {response: {status, headers, body, body_encoding}}. Common echoes of input secrets are redacted;',
    '     do not treat redaction as protection against arbitrary transformations by an untrusted destination.',
    '     Optional save: "<name>" stores the response body and returns only response status/headers and saved metadata.',
    '     Redirects are returned, not followed.',
    '     HTTPS on 443, public hostnames only, never this server or private networks. 1MB each way, 20 seconds, 30/minute.',
    '     No workflow, schedule or implicit execution: the caller chooses each invocation and each saved output.', '',
    'THE SHELL (only if you can run commands)',
    '   Install: npm install -g @tomato414941/foundation   (Node.js 24 or later)',
    '   foundation connect [<url>] [--name <name>]',
    '     Makes the key as a private file and asks for approval. The key is never printed, so it never reaches you.',
    '     Given a URL, it also remembers that server for every later command; run it again when the server moves.',
    '   foundation api <GET|POST|PUT|DELETE|PATCH> </path> [--json <body>] [--from <file>] [--type <media-type>]',
    '     Any request above, with the key attached and the answer printed as it came. Prefer this over curl: reading the key',
    '     file to build a header yourself would put the key in your context, which is the thing this avoids.',
    '   foundation exec <ENV>=<name> [...] -- <command> [args...]',
    `   foundation exec --inputs '[{"name":"signing key","as":"KEY_FILE","filename":"AuthKey.p8"}]' -- <command>`,
    '     ENV=name treats everything after the first = literally. Use --inputs JSON for files or structured inputs.',
    '     Only the child process gets delivered values; files exist only while it runs. FOUNDATION_NAMES is a JSON array',
    '     of the exact saved names used. Prevent the child command from logging or echoing secrets.',
    '     Use this instead of POST /v1/deliveries whenever the point is to run something.',
    `   foundation exec --output '{"name":"login config","as":"AUTH_FILE","filename":"auth.json"}' -- <command>`,
    '     Creates one empty private file and sets as to its path. Tell the command to write its authentication result there.',
    '     After exit 0, saves the file bytes under the exact name with secret=true, then removes the temporary file.',
    '     An existing value at that name is replaced. Output must be a private regular file containing 1 byte to 1MB.',
    '     May be combined with inputs, using a different environment variable. A failed command never saves its output.',
    '     If upload cannot be confirmed, exits with an error and reports the retained private file for recovery; inputs are',
    '     still removed. Retry with api PUT --from, then remove the recovery file. Other temporary files are removed.',
    '     Use native service login URLs; never collect passwords in chat. Stored credentials keep their original expiry.',
    '   Environment: FOUNDATION_URL (optional; overrides the remembered server), FOUNDATION_AGENT (optional; your name, e.g. claude / codex), FOUNDATION_RUNTIME_KEY_FILE (optional).',
    '   One key per machine and OS user by default. FOUNDATION_AGENT gives each agent its own key, but any agent running as the',
    '   same OS user can read that file, so it is bookkeeping, not protection. To separate them for real, use separate OS users.', '',
    'RULES',
    '- Never print, log or write out what is delivered. Hand it to a command, and nowhere else.',
    '- Send saved values only to an authorized destination. http.request and exec use the destinations you choose.',
    '- Ask for the least you need. Do not request something the work does not use.',
    '- Be honest in name, purpose and label. The owner decides based on them.',
    '- If a request is denied or expires, ask the owner why rather than guessing.',
    '- Use what you receive only for the work it was asked for.',
  ].join('\n');
}
