import { type RouteConfig, index, route } from '@react-router/dev/routes';
export default [
  index('routes/index.tsx'),
  route('signin', 'routes/signin.tsx'),
  route('signin/email', 'routes/email.tsx'),
  route('account', 'routes/account.tsx'),
  route('account/trust', 'routes/trust.tsx'),
  route('account/merge/:id', 'routes/merge.tsx'),
  route('requests', 'routes/requests.tsx'),
  route('requests/new', 'routes/request-new.tsx'),
  route('requests/:id', 'routes/request.tsx'),
  route('devices/:id', 'routes/device.tsx'),
  route('services', 'routes/service-return.tsx'),
  route('connections/complete', 'routes/connection-complete.tsx'),
  route('connections/:id', 'routes/connection-flow.tsx'),
  route('shared', 'routes/shared.tsx'),
  route('runs/:id', 'routes/run.tsx'),
  route('p/:owner', 'routes/workspace.tsx', [
    index('routes/home.tsx'),
    route('principals', 'routes/principals.tsx'),
    route('principals/new', 'routes/principal-new.tsx'),
    route('settings/:tab', 'routes/settings.tsx'),
    route('settings/:tab/new', 'routes/credential-new.tsx'),
    route('settings/general/share', 'routes/principal-share.tsx'),
    route('runs', 'routes/runs.tsx'),
    route('runs/new', 'routes/run-new.tsx'),
    route(':section', 'routes/resource-list.tsx'),
    route(':section/new', 'routes/resource-form.tsx'),
    route(':section/:id', 'routes/resource.tsx'),
    route(':section/:id/edit', 'routes/resource-edit.tsx'),
    route(':section/:id/share', 'routes/resource-share.tsx'),
    route(':section/:id/transfer', 'routes/resource-transfer.tsx'),
    route('functions/:id/run', 'routes/resource-run.tsx'),
  ]),
  route('*', 'routes/not-found.tsx'),
] satisfies RouteConfig;
