export const serviceLabels: Record<string, string> = {
  'airtable.token.token.label': 'Personal access token',
  'asana.token.token.label': 'Personal access token',
  'atlassian.token.site.label': 'サイト',
  'atlassian.token.site.placeholder': 'example.atlassian.net',
  'atlassian.token.email.label': 'Atlassianアカウントのメールアドレス',
  'atlassian.token.token.label': 'APIトークン',
  'bitbucket.token.email.label': 'Atlassianアカウントのメールアドレス',
  'bitbucket.token.token.label': 'APIトークン',
  'calendly.token.token.label': 'Personal access token',
  'chatwork.token.token.label': 'APIトークン',
  'cloudflare.token.token.label': 'APIトークン',
  'digitalocean.token.token.label': 'Personal access token',
  'discord.token.token.label': 'Bot token',
  'ebay.oauth.ru_name.label': 'RuName',
  'github.token.token.label': 'Personal access token',
  'gitlab.token.token.label': 'Personal access token',
  'heroku.token.token.label': 'API key',
  'hubspot.token.token.label': 'Private app access token',
  'kintone.oauth.domain.label': 'kintoneのドメイン',
  'kintone.oauth.domain.placeholder': 'example.cybozu.com',
  'kintone.token.domain.label': 'kintoneのドメイン',
  'kintone.token.domain.placeholder': 'example.cybozu.com',
  'kintone.token.token.label': 'APIトークン',
  'linear.token.token.label': 'Personal API key',
  'microsoft.oauth.tenant.label': 'テナント（任意）',
  'microsoft.oauth.tenant.note':
    '組織のアカウントだけに限るときに、テナントIDを入れます。空なら個人と組織の両方のアカウントで使えます。',
  'netlify.token.token.label': 'Personal access token',
  'notion.token.token.label': '内部インテグレーションのシークレット',
  'openrouter.token.token.label': 'APIキー',
  'sakura-vps.token.token.label': 'APIキー',
  'sakura-vps.token.token.note':
    'さくらのVPSのAPIキーを入力してください。さくらのクラウドのAPIキーとは異なります。',
  'shopify.oauth.shop.label': 'ストア名',
  'shopify.oauth.shop.placeholder': 'example（example.myshopify.com の場合）',
  'shopify.token.shop.label': 'ストア名',
  'shopify.token.shop.placeholder': 'example（example.myshopify.com の場合）',
  'shopify.token.token.label': 'Admin APIのアクセストークン',
  'slack.token.token.label': 'Bot User OAuth Token',
  'x.token.token.label': 'Bearer Token',
  'xserver.token.token.label': 'APIキー',
  'xserver.token.token.note': 'xs_で始まるAPIキーを入力してください。',
  'zendesk.oauth.subdomain.label': 'サブドメイン',
  'zendesk.oauth.subdomain.placeholder': 'example（example.zendesk.com の場合）',
  'zendesk.token.subdomain.label': 'サブドメイン',
  'zendesk.token.subdomain.placeholder': 'example（example.zendesk.com の場合）',
  'zendesk.token.email.label': 'Zendeskのメールアドレス',
  'zendesk.token.token.label': 'APIトークン',
};
