import { useState } from 'react';
import { Form, Link, useActionData, useLoaderData } from 'react-router';
import type { ActionFunctionArgs, LoaderFunctionArgs } from 'react-router';
import { Button, Checkbox, FormControlLabel, FormGroup, List, ListItem, ListItemText, Stack, TextField, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { Action, Grant, Principal, Resource, listOf } from '../../shared/contracts';
import type { ActionName } from '../../shared/contracts';
import { actionResult, api, ApiFailure, formText, session } from './api';
import { decryptSecret, sealSecret } from './keys';
import { Copy, ErrorNotice, Page, Panel, SaveBar } from './components';
import { resourcePath } from './navigation';
export async function shareLoader({ params, request }: LoaderFunctionArgs) { const prefix = params.id ? '/resources/' + params.id : '/principals/' + params.owner; const [target, grants] = await Promise.all([params.id ? api(prefix, { signal: request.signal }, Resource) : api(prefix, { signal: request.signal }, Principal), api(prefix + '/grants', { signal: request.signal }, listOf(Grant))]); return { target, grants: grants.items, prefix }; }
export async function shareAction({ params, request }: ActionFunctionArgs) { return actionResult(async () => { const form = await request.formData(); const prefix = params.id ? '/resources/' + params.id : '/principals/' + params.owner; const id = formText(form, 'principalId'); const remove = formText(form, 'intent') === 'remove'; const actions = form.getAll('actions').map(value => Action.parse(value)); if (!remove && !actions.length) throw new ApiFailure('invalid_input'); if (params.id && actions.includes('reveal')) { const resource = await api('/resources/' + params.id, {}, Resource); if (resource.kind === 'secret' && !resource.data.recipients.includes(id)) { const data = await session(); const content = await decryptSecret(resource.id, data.principal!.id); const sealed = await sealSecret(resource.id, resource.ownerId, content, data.server, resource.data.allowUse, [...resource.data.recipients, id], true); await api('/resources/' + resource.id, { method: 'PATCH', body: { version: resource.version, sealed, bytes: content.length } }); } } await api(prefix + '/grants/' + id, { method: remove ? 'DELETE' : 'PUT', ...(remove ? {} : { body: { actions } }) }); return { ok: true }; }); }
export default function Sharing() { const { t } = useTranslation(); const data = useLoaderData<typeof shareLoader>(); const result = useActionData<typeof shareAction>(); const [id, setId] = useState(''); const [actions, setActions] = useState<ActionName[]>(['read']); const back = 'kind' in data.target ? resourcePath(data.target) : '/p/' + data.target.id + '/settings/general'; return <Page title={t('share') + ' — ' + data.target.name} narrow><ErrorNotice error={result && 'error' in result ? result.error : null} /><Panel title={t('granted')}><List disablePadding>{data.grants.map(grant => <ListItem key={grant.principalId} disableGutters sx={{ flexWrap: 'wrap', gap: 1 }}><ListItemText primary={grant.principalName ?? grant.principalId} secondary={grant.actions.map(action => t('permission.' + action)).join('、')} /><Button onClick={() => { setId(grant.principalId); setActions(grant.actions); }}>{t('edit')}</Button><Form method="post"><input type="hidden" name="principalId" value={grant.principalId} /><Button type="submit" name="intent" value="remove" color="error">{t('removeAccess')}</Button></Form></ListItem>)}</List>{!data.grants.length && <Typography color="text.secondary">{t('empty')}</Typography>}</Panel><Form method="post"><Stack spacing={3}><TextField name="principalId" label={t('recipient')} value={id} onChange={event => setId(event.target.value)} required fullWidth /><Panel title={t('permissions')}><FormGroup>{data.target.permissions.filter(action => 'kind' in data.target || !['delete', 'transfer'].includes(action)).map(action => <FormControlLabel key={action} label={t('permission.' + action)} control={<Checkbox name="actions" value={action} checked={actions.includes(action)} onChange={event => setActions(event.target.checked ? [...actions, action] : actions.filter(value => value !== action))} />} />)}</FormGroup></Panel><SaveBar back={back} label="grant" /></Stack></Form></Page>; }
